use core::fmt;

#[derive(Debug, PartialEq)]
pub enum DeviceType {
    Other,
    OilMeter,
    ElectricityMeter,
    GasMeter,
    HeatMeter,
    SteamMeter,
    WarmWaterMeter,
    WaterMeter,
    HeatCostAllocator,
    CompressedAir,
    CoolingMeter,
    Cooling2Meter,
    Heat2Meter,
    HeatCooling,
    BusSystem,
    Unknown,
    ReservedConsumptionMeter0x10,
    ReservedConsumptionMeter0x11,
    ReservedConsumptionMeter0x13,
    ReservedConsumptionMeter0x14,
    CalorificValue,
    HotWaterMeter,
    ColdWater,
    DualWater,
    Pressure,
    ADConverter,
    SmokeDetector,
    RoomSensor,
    GasDetector,
    ReservedSensor0x1D,
    ReservedSensor0x1E,
    ReservedSensor0x1F,
    CircuitBreaker,
    Valve,
    ReservedSwitching0x22,
    ReservedSwitching0x23,
    ReservedSwitching0x24,
    Display,
    ReservedCustomer0x26,
    ReservedCustomer0x27,
    WasteWaterMeter,
    Garbage,
    CarbonDioxide,
    ReservedEnvironmentalMeter0x2B,
    ReservedEnvironmentalMeter0x2C,
    ReservedEnvironmentalMeter0x2D,
    ReservedEnvironmentalMeter0x2E,
    ReservedEnvironmentalMeter0x2F,
    ReservedSystemDevices0x30,
    CommunicationControler,
    UnidirectionalRepeater,
    BidirectionalRepeater,
    ReservedSystemDevices0x34,
    ReservedSystemDevices0x35,
    RadioConverterSystem,
    RadioConverter,
    ReservedSystemDevices0x38,
    ReservedSystemDevices0x39,
    ReservedSystemDevices0x3A,
    ReservedSystemDevices0x3B,
    ReservedSystemDevices0x3C,
    ReservedSystemDevices0x3D,
    ReservedSystemDevices0x3E,
    ReservedSystemDevices0x3F,
    Reserved0x40,
    Reserved0x41,
    Reserved0x42,
    Reserved0x43,
    Reserved0x44,
    Reserved0x45,
    Reserved0x46,
    Reserved0x47,
    Reserved0x48,
    Reserved0x49,
    Reserved0x4A,
    Reserved0x4B,
    Reserved0x4C,
    Reserved0x4D,
    Reserved0x4E,
    Reserved0x4F,
    Reserved0x50,
    Reserved0x51,
    Reserved0x52,
    Reserved0x53,
    Reserved0x54,
    Reserved0x55,
    Reserved0x56,
    Reserved0x57,
    Reserved0x58,
    Reserved0x59,
    Reserved0x5A,
    Reserved0x5B,
    Reserved0x5C,
    Reserved0x5D,
    Reserved0x5E,
    Reserved0x5F,
    Reserved0x60,
    Reserved0x61,
    Reserved0x62,
    Reserved0x63,
    Reserved0x64,
    Reserved0x65,
    Reserved0x66,
    Reserved0x67,
    Reserved0x68,
    Reserved0x69,
    Reserved0x6A,
    Reserved0x6B,
    Reserved0x6C,
    Reserved0x6D,
    Reserved0x6E,
    Reserved0x6F,
    Reserved0x70,
    Reserved0x71,
    Reserved0x72,
    Reserved0x73,
    Reserved0x74,
    Reserved0x75,
    Reserved0x76,
    Reserved0x77,
    Reserved0x78,
    Reserved0x79,
    Reserved0x7A,
    Reserved0x7B,
    Reserved0x7C,
    Reserved0x7D,
    Reserved0x7E,
    Reserved0x7F,
    Reserved0x80,
    Reserved0x81,
    Reserved0x82,
    Reserved0x83,
    Reserved0x84,
    Reserved0x85,
    Reserved0x86,
    Reserved0x87,
    Reserved0x88,
    Reserved0x89,
    Reserved0x8A,
    Reserved0x8B,
    Reserved0x8C,
    Reserved0x8D,
    Reserved0x8E,
    Reserved0x8F,
    Reserved0x90,
    Reserved0x91,
    Reserved0x92,
    Reserved0x93,
    Reserved0x94,
    Reserved0x95,
    Reserved0x96,
    Reserved0x97,
    Reserved0x98,
    Reserved0x99,
    Reserved0x9A,
    Reserved0x9B,
    Reserved0x9C,
    Reserved0x9D,
    Reserved0x9E,
    Reserved0x9F,
    Reserved0xA0,
    Reserved0xA1,
    Reserved0xA2,
    Reserved0xA3,
    Reserved0xA4,
    Reserved0xA5,
    Reserved0xA6,
    Reserved0xA7,
    Reserved0xA8,
    Reserved0xA9,
    Reserved0xAA,
    Reserved0xAB,
    Reserved0xAC,
    Reserved0xAD,
    Reserved0xAE,
    Reserved0xAF,
    Reserved0xB0,
    Reserved0xB1,
    Reserved0xB2,
    Reserved0xB3,
    Reserved0xB4,
    Reserved0xB5,
    Reserved0xB6,
    Reserved0xB7,
    Reserved0xB8,
    Reserved0xB9,
    Reserved0xBA,
    Reserved0xBB,
    Reserved0xBC,
    Reserved0xBD,
    Reserved0xBE,
    Reserved0xBF,
    Reserved0xC0,
    Reserved0xC1,
    Reserved0xC2,
    Reserved0xC3,
    Reserved0xC4,
    Reserved0xC5,
    Reserved0xC6,
    Reserved0xC7,
    Reserved0xC8,
    Reserved0xC9,
    Reserved0xCA,
    Reserved0xCB,
    Reserved0xCC,
    Reserved0xCD,
    Reserved0xCE,
    Reserved0xCF,
    Reserved0xD0,
    Reserved0xD1,
    Reserved0xD2,
    Reserved0xD3,
    Reserved0xD4,
    Reserved0xD5,
    Reserved0xD6,
    Reserved0xD7,
    Reserved0xD8,
    Reserved0xD9,
    Reserved0xDA,
    Reserved0xDB,
    Reserved0xDC,
    Reserved0xDD,
    Reserved0xDE,
    Reserved0xDF,
    Reserved0xE0,
    Reserved0xE1,
    Reserved0xE2,
    Reserved0xE3,
    Reserved0xE4,
    Reserved0xE5,
    Reserved0xE6,
    Reserved0xE7,
    Reserved0xE8,
    Reserved0xE9,
    Reserved0xEA,
    Reserved0xEB,
    Reserved0xEC,
    Reserved0xED,
    Reserved0xEE,
    Reserved0xEF,
    Reserved0xF0,
    Reserved0xF1,
    Reserved0xF2,
    Reserved0xF3,
    Reserved0xF4,
    Reserved0xF5,
    Reserved0xF6,
    Reserved0xF7,
    Reserved0xF8,
    Reserved0xF9,
    Reserved0xFA,
    Reserved0xFB,
    Reserved0xFC,
    Reserved0xFD,
    Reserved0xFE,
    Reserved0xFF,
}

impl DeviceType {
    pub fn new(input: u8) -> DeviceType {
        match input {
            0x00 => DeviceType::Other,
            0x01 => DeviceType::OilMeter,
            0x02 => DeviceType::ElectricityMeter,
            0x03 => DeviceType::GasMeter,
            0x04 => DeviceType::HeatMeter,
            0x05 => DeviceType::SteamMeter,
            0x06 => DeviceType::WarmWaterMeter,
            0x07 => DeviceType::WaterMeter,
            0x08 => DeviceType::HeatCostAllocator,
            0x09 => DeviceType::CompressedAir,
            0x0A => DeviceType::CoolingMeter,
            0x0B => DeviceType::Cooling2Meter,
            0x0C => DeviceType::Heat2Meter,
            0x0D => DeviceType::HeatCooling,
            0x0E => DeviceType::BusSystem,
            0x0F => DeviceType::Unknown,
            0x10 => DeviceType::ReservedConsumptionMeter0x10,
            0x11 => DeviceType::ReservedConsumptionMeter0x11,
            0x12 => DeviceType::ReservedConsumptionMeter0x13,
            0x13 => DeviceType::ReservedConsumptionMeter0x14,
            0x14 => DeviceType::CalorificValue,
            0x15 => DeviceType::HotWaterMeter,
            0x16 => DeviceType::ColdWater,
            0x17 => DeviceType::DualWater,
            0x18 => DeviceType::Pressure,
            0x19 => DeviceType::ADConverter,
            0x1A => DeviceType::SmokeDetector,
            0x1B => DeviceType::RoomSensor,
            0x1C => DeviceType::GasDetector,
            0x1D => DeviceType::ReservedSensor0x1D,
            0x1E => DeviceType::ReservedSensor0x1E,
            0x1F => DeviceType::ReservedSensor0x1F,
            0x20 => DeviceType::CircuitBreaker,
            0x21 => DeviceType::Valve,
            0x22 => DeviceType::ReservedSwitching0x22,
            0x23 => DeviceType::ReservedSwitching0x23,
            0x24 => DeviceType::ReservedSwitching0x24,
            0x25 => DeviceType::Display,
            0x26 => DeviceType::ReservedCustomer0x26,
            0x27 => DeviceType::ReservedCustomer0x27,
            0x28 => DeviceType::WasteWaterMeter,
            0x29 => DeviceType::Garbage,
            0x2A => DeviceType::CarbonDioxide,
            0x2B => DeviceType::ReservedEnvironmentalMeter0x2B,
            0x2C => DeviceType::ReservedEnvironmentalMeter0x2C,
            0x2D => DeviceType::ReservedEnvironmentalMeter0x2D,
            0x2E => DeviceType::ReservedEnvironmentalMeter0x2E,
            0x2F => DeviceType::ReservedEnvironmentalMeter0x2F,
            0x30 => DeviceType::ReservedSystemDevices0x30,
            0x31 => DeviceType::CommunicationControler,
            0x32 => DeviceType::UnidirectionalRepeater,
            0x33 => DeviceType::BidirectionalRepeater,
            0x34 => DeviceType::ReservedSystemDevices0x34,
            0x35 => DeviceType::ReservedSystemDevices0x35,
            0x36 => DeviceType::RadioConverterSystem,
            0x37 => DeviceType::RadioConverter,
            0x38 => DeviceType::ReservedSystemDevices0x38,
            0x39 => DeviceType::ReservedSystemDevices0x39,
            0x3A => DeviceType::ReservedSystemDevices0x3A,
            0x3B => DeviceType::ReservedSystemDevices0x3B,
            0x3C => DeviceType::ReservedSystemDevices0x3C,
            0x3D => DeviceType::ReservedSystemDevices0x3D,
            0x3E => DeviceType::ReservedSystemDevices0x3E,
            0x3F => DeviceType::ReservedSystemDevices0x3F,
            0x40 => DeviceType::Reserved0x40,
            0x41 => DeviceType::Reserved0x41,
            0x42 => DeviceType::Reserved0x42,
            0x43 => DeviceType::Reserved0x43,
            0x44 => DeviceType::Reserved0x44,
            0x45 => DeviceType::Reserved0x45,
            0x46 => DeviceType::Reserved0x46,
            0x47 => DeviceType::Reserved0x47,
            0x48 => DeviceType::Reserved0x48,
            0x49 => DeviceType::Reserved0x49,
            0x4A => DeviceType::Reserved0x4A,
            0x4B => DeviceType::Reserved0x4B,
            0x4C => DeviceType::Reserved0x4C,
            0x4D => DeviceType::Reserved0x4D,
            0x4E => DeviceType::Reserved0x4E,
            0x4F => DeviceType::Reserved0x4F,
            0x50 => DeviceType::Reserved0x50,
            0x51 => DeviceType::Reserved0x51,
            0x52 => DeviceType::Reserved0x52,
            0x53 => DeviceType::Reserved0x53,
            0x54 => DeviceType::Reserved0x54,
            0x55 => DeviceType::Reserved0x55,
            0x56 => DeviceType::Reserved0x56,
            0x57 => DeviceType::Reserved0x57,
            0x58 => DeviceType::Reserved0x58,
            0x59 => DeviceType::Reserved0x59,
            0x5A => DeviceType::Reserved0x5A,
            0x5B => DeviceType::Reserved0x5B,
            0x5C => DeviceType::Reserved0x5C,
            0x5D => DeviceType::Reserved0x5D,
            0x5E => DeviceType::Reserved0x5E,
            0x5F => DeviceType::Reserved0x5F,
            0x60 => DeviceType::Reserved0x60,
            0x61 => DeviceType::Reserved0x61,
            0x62 => DeviceType::Reserved0x62,
            0x63 => DeviceType::Reserved0x63,
            0x64 => DeviceType::Reserved0x64,
            0x65 => DeviceType::Reserved0x65,
            0x66 => DeviceType::Reserved0x66,
            0x67 => DeviceType::Reserved0x67,
            0x68 => DeviceType::Reserved0x68,
            0x69 => DeviceType::Reserved0x69,
            0x6A => DeviceType::Reserved0x6A,
            0x6B => DeviceType::Reserved0x6B,
            0x6C => DeviceType::Reserved0x6C,
            0x6D => DeviceType::Reserved0x6D,
            0x6E => DeviceType::Reserved0x6E,
            0x6F => DeviceType::Reserved0x6F,
            0x70 => DeviceType::Reserved0x70,
            0x71 => DeviceType::Reserved0x71,
            0x72 => DeviceType::Reserved0x72,
            0x73 => DeviceType::Reserved0x73,
            0x74 => DeviceType::Reserved0x74,
            0x75 => DeviceType::Reserved0x75,
            0x76 => DeviceType::Reserved0x76,
            0x77 => DeviceType::Reserved0x77,
            0x78 => DeviceType::Reserved0x78,
            0x79 => DeviceType::Reserved0x79,
            0x7A => DeviceType::Reserved0x7A,
            0x7B => DeviceType::Reserved0x7B,
            0x7C => DeviceType::Reserved0x7C,
            0x7D => DeviceType::Reserved0x7D,
            0x7E => DeviceType::Reserved0x7E,
            0x7F => DeviceType::Reserved0x7F,
            0x80 => DeviceType::Reserved0x80,
            0x81 => DeviceType::Reserved0x81,
            0x82 => DeviceType::Reserved0x82,
            0x83 => DeviceType::Reserved0x83,
            0x84 => DeviceType::Reserved0x84,
            0x85 => DeviceType::Reserved0x85,
            0x86 => DeviceType::Reserved0x86,
            0x87 => DeviceType::Reserved0x87,
            0x88 => DeviceType::Reserved0x88,
            0x89 => DeviceType::Reserved0x89,
            0x8A => DeviceType::Reserved0x8A,
            0x8B => DeviceType::Reserved0x8B,
            0x8C => DeviceType::Reserved0x8C,
            0x8D => DeviceType::Reserved0x8D,
            0x8E => DeviceType::Reserved0x8E,
            0x8F => DeviceType::Reserved0x8F,
            0x90 => DeviceType::Reserved0x90,
            0x91 => DeviceType::Reserved0x91,
            0x92 => DeviceType::Reserved0x92,
            0x93 => DeviceType::Reserved0x93,
            0x94 => DeviceType::Reserved0x94,
            0x95 => DeviceType::Reserved0x95,
            0x96 => DeviceType::Reserved0x96,
            0x97 => DeviceType::Reserved0x97,
            0x98 => DeviceType::Reserved0x98,
            0x99 => DeviceType::Reserved0x99,
            0x9A => DeviceType::Reserved0x9A,
            0x9B => DeviceType::Reserved0x9B,
            0x9C => DeviceType::Reserved0x9C,
            0x9D => DeviceType::Reserved0x9D,
            0x9E => DeviceType::Reserved0x9E,
            0x9F => DeviceType::Reserved0x9F,
            0xA0 => DeviceType::Reserved0xA0,
            0xA1 => DeviceType::Reserved0xA1,
            0xA2 => DeviceType::Reserved0xA2,
            0xA3 => DeviceType::Reserved0xA3,
            0xA4 => DeviceType::Reserved0xA4,
            0xA5 => DeviceType::Reserved0xA5,
            0xA6 => DeviceType::Reserved0xA6,
            0xA7 => DeviceType::Reserved0xA7,
            0xA8 => DeviceType::Reserved0xA8,
            0xA9 => DeviceType::Reserved0xA9,
            0xAA => DeviceType::Reserved0xAA,
            0xAB => DeviceType::Reserved0xAB,
            0xAC => DeviceType::Reserved0xAC,
            0xAD => DeviceType::Reserved0xAD,
            0xAE => DeviceType::Reserved0xAE,
            0xAF => DeviceType::Reserved0xAF,
            0xB0 => DeviceType::Reserved0xB0,
            0xB1 => DeviceType::Reserved0xB1,
            0xB2 => DeviceType::Reserved0xB2,
            0xB3 => DeviceType::Reserved0xB3,
            0xB4 => DeviceType::Reserved0xB4,
            0xB5 => DeviceType::Reserved0xB5,
            0xB6 => DeviceType::Reserved0xB6,
            0xB7 => DeviceType::Reserved0xB7,
            0xB8 => DeviceType::Reserved0xB8,
            0xB9 => DeviceType::Reserved0xB9,
            0xBA => DeviceType::Reserved0xBA,
            0xBB => DeviceType::Reserved0xBB,
            0xBC => DeviceType::Reserved0xBC,
            0xBD => DeviceType::Reserved0xBD,
            0xBE => DeviceType::Reserved0xBE,
            0xBF => DeviceType::Reserved0xBF,
            0xC0 => DeviceType::Reserved0xC0,
            0xC1 => DeviceType::Reserved0xC1,
            0xC2 => DeviceType::Reserved0xC2,
            0xC3 => DeviceType::Reserved0xC3,
            0xC4 => DeviceType::Reserved0xC4,
            0xC5 => DeviceType::Reserved0xC5,
            0xC6 => DeviceType::Reserved0xC6,
            0xC7 => DeviceType::Reserved0xC7,
            0xC8 => DeviceType::Reserved0xC8,
            0xC9 => DeviceType::Reserved0xC9,
            0xCA => DeviceType::Reserved0xCA,
            0xCB => DeviceType::Reserved0xCB,
            0xCC => DeviceType::Reserved0xCC,
            0xCD => DeviceType::Reserved0xCD,
            0xCE => DeviceType::Reserved0xCE,
            0xCF => DeviceType::Reserved0xCF,
            0xD0 => DeviceType::Reserved0xD0,
            0xD1 => DeviceType::Reserved0xD1,
            0xD2 => DeviceType::Reserved0xD2,
            0xD3 => DeviceType::Reserved0xD3,
            0xD4 => DeviceType::Reserved0xD4,
            0xD5 => DeviceType::Reserved0xD5,
            0xD6 => DeviceType::Reserved0xD6,
            0xD7 => DeviceType::Reserved0xD7,
            0xD8 => DeviceType::Reserved0xD8,
            0xD9 => DeviceType::Reserved0xD9,
            0xDA => DeviceType::Reserved0xDA,
            0xDB => DeviceType::Reserved0xDB,
            0xDC => DeviceType::Reserved0xDC,
            0xDD => DeviceType::Reserved0xDD,
            0xDE => DeviceType::Reserved0xDE,
            0xDF => DeviceType::Reserved0xDF,
            0xE0 => DeviceType::Reserved0xE0,
            0xE1 => DeviceType::Reserved0xE1,
            0xE2 => DeviceType::Reserved0xE2,
            0xE3 => DeviceType::Reserved0xE3,
            0xE4 => DeviceType::Reserved0xE4,
            0xE5 => DeviceType::Reserved0xE5,
            0xE6 => DeviceType::Reserved0xE6,
            0xE7 => DeviceType::Reserved0xE7,
            0xE8 => DeviceType::Reserved0xE8,
            0xE9 => DeviceType::Reserved0xE9,
            0xEA => DeviceType::Reserved0xEA,
            0xEB => DeviceType::Reserved0xEB,
            0xEC => DeviceType::Reserved0xEC,
            0xED => DeviceType::Reserved0xED,
            0xEE => DeviceType::Reserved0xEE,
            0xEF => DeviceType::Reserved0xEF,
            0xF0 => DeviceType::Reserved0xF0,
            0xF1 => DeviceType::Reserved0xF1,
            0xF2 => DeviceType::Reserved0xF2,
            0xF3 => DeviceType::Reserved0xF3,
            0xF4 => DeviceType::Reserved0xF4,
            0xF5 => DeviceType::Reserved0xF5,
            0xF6 => DeviceType::Reserved0xF6,
            0xF7 => DeviceType::Reserved0xF7,
            0xF8 => DeviceType::Reserved0xF8,
            0xF9 => DeviceType::Reserved0xF9,
            0xFA => DeviceType::Reserved0xFA,
            0xFB => DeviceType::Reserved0xFB,
            0xFC => DeviceType::Reserved0xFC,
            0xFD => DeviceType::Reserved0xFD,
            0xFE => DeviceType::Reserved0xFE,
            0xFF => DeviceType::Reserved0xFF,
        }
    }
}

impl fmt::Display for DeviceType {
    fn fmt(&self, f: &mut fmt::Formatter<'_>) -> fmt::Result {
        let device_type: &str = match self {
            DeviceType::Other => "Other",
            DeviceType::OilMeter => "Oil meter",
            DeviceType::ElectricityMeter => "Electricity meter",
            DeviceType::GasMeter => "Gas meter",
            DeviceType::HeatMeter => "Heat meter",
            DeviceType::SteamMeter => "Steam meter",
            DeviceType::WarmWaterMeter => "Warm water meter",
            DeviceType::WaterMeter => "Water meter",
            DeviceType::HeatCostAllocator => "Heat cost allocator",
            DeviceType::CompressedAir => "Compressed air",
            DeviceType::CoolingMeter => "Cooling meter (volume measured at return temperature: outlet",
            DeviceType::Cooling2Meter => "Cooling meter (Volume measured at flow temperature: inlet)",
            DeviceType::Heat2Meter => "Heat meter (volume measured at flow temperature: inlet",
            DeviceType::HeatCooling => "Combined heat/cooling meter",
            DeviceType::BusSystem => "Bus/system component",
            DeviceType::Unknown => "Unknown device type",
            DeviceType::ReservedConsumptionMeter0x10 => "Reserved for consumption meter 10h",
            DeviceType::ReservedConsumptionMeter0x11 => "Reserved for consumption meter 11h",
            DeviceType::ReservedConsumptionMeter0x13 => "Reserved for consumption meter 12h",
            DeviceType::ReservedConsumptionMeter0x14 => "Reserved for consumption meter 13h",
            DeviceType::CalorificValue => "Calorific value",
            DeviceType::HotWaterMeter => "Hot water meter",
            DeviceType::ColdWater => "Cold water meter",
            DeviceType::DualWater => "Dual register hot/cold water meter",
            DeviceType::Pressure => "Pressure meter",
            DeviceType::ADConverter => "A/D converter",
            DeviceType::SmokeDetector => "Smoke detector",
            DeviceType::RoomSensor => "Room sensor",
            DeviceType::GasDetector => "Gas detector",
            DeviceType::ReservedSensor0x1D => "Reserved for sensors 1Dh",
            DeviceType::ReservedSensor0x1E => "Reserved for sensors 1Eh",
            DeviceType::ReservedSensor0x1F => "Reserved for sensors 1Fh",
            DeviceType::CircuitBreaker => "Breaker (electricity)",
            DeviceType::Valve => "Valve (gas or water)",
            DeviceType::ReservedSwitching0x22 => "Reserved for switching devices 22h",
            DeviceType::ReservedSwitching0x23 => "Reserved for switching devices 23h",
            DeviceType::ReservedSwitching0x24 => "Reserved for switching devices 24h",
            DeviceType::Display => "Customer unit (display device)",
            DeviceType::ReservedCustomer0x26 => "Reserved for customer units 26h",
            DeviceType::ReservedCustomer0x27 => "Reserved for customer units 27h",
            DeviceType::WasteWaterMeter => "Waste water meter",
            DeviceType::Garbage => "Garbage",
            DeviceType::CarbonDioxide => "Carbon dioxide",
            DeviceType::ReservedEnvironmentalMeter0x2B => "Reserved for environmental meter 2Bh",
            DeviceType::ReservedEnvironmentalMeter0x2C => "Reserved for environmental meter 2Ch",
            DeviceType::ReservedEnvironmentalMeter0x2D => "Reserved for environmental meter 2Dh",
            DeviceType::ReservedEnvironmentalMeter0x2E => "Reserved for environmental meter 2Eh",
            DeviceType::ReservedEnvironmentalMeter0x2F => "Reserved for environmental meter 2Fh",
            DeviceType::ReservedSystemDevices0x30 => "Reserved for system devices 30h",
            DeviceType::CommunicationControler => "Communication controler (gateway)",
            DeviceType::UnidirectionalRepeater => "Unidirectional repeater",
            DeviceType::BidirectionalRepeater => "Bidirectional repeater",
            DeviceType::ReservedSystemDevices0x34 => "Reserved for system devices 34h",
            DeviceType::ReservedSystemDevices0x35 => "Reserved for system devices 35h",
            DeviceType::RadioConverterSystem => "Radio converter (system side)",
            DeviceType::RadioConverter => "Radio converter (meter side)",
            DeviceType::ReservedSystemDevices0x38 => "Reserved for system devices 38h",
            DeviceType::ReservedSystemDevices0x39 => "Reserved for system devices 39h",
            DeviceType::ReservedSystemDevices0x3A => "Reserved for system devices 3Ah",
            DeviceType::ReservedSystemDevices0x3B => "Reserved for system devices 3Bh",
            DeviceType::ReservedSystemDevices0x3C => "Reserved for system devices 3Ch",
            DeviceType::ReservedSystemDevices0x3D => "Reserved for system devices 3Dh",
            DeviceType::ReservedSystemDevices0x3E => "Reserved for system devices 3Eh",
            DeviceType::ReservedSystemDevices0x3F => "Reserved for system devices 3Fh",
            DeviceType::Reserved0x40 => "Reserved 40h",
            DeviceType::Reserved0x41 => "Reserved 41h",
            DeviceType::Reserved0x42 => "Reserved 42h",
            DeviceType::Reserved0x43 => "Reserved 43h",
            DeviceType::Reserved0x44 => "Reserved 44h",
            DeviceType::Reserved0x45 => "Reserved 45h",
            DeviceType::Reserved0x46 => "Reserved 46h",
            DeviceType::Reserved0x47 => "Reserved 47h",
            DeviceType::Reserved0x48 => "Reserved 48h",
            DeviceType::Reserved0x49 => "Reserved 49h",
            DeviceType::Reserved0x4A => "Reserved 4Ah",
            DeviceType::Reserved0x4B => "Reserved 4Bh",
            DeviceType::Reserved0x4C => "Reserved 4Ch",
            DeviceType::Reserved0x4D => "Reserved 4Dh",
            DeviceType::Reserved0x4E => "Reserved 4Eh",
            DeviceType::Reserved0x4F => "Reserved 4Fh",
            DeviceType::Reserved0x50 => "Reserved 50h",
            DeviceType::Reserved0x51 => "Reserved 51h",
            DeviceType::Reserved0x52 => "Reserved 52h",
            DeviceType::Reserved0x53 => "Reserved 53h",
            DeviceType::Reserved0x54 => "Reserved 54h",
            DeviceType::Reserved0x55 => "Reserved 55h",
            DeviceType::Reserved0x56 => "Reserved 56h",
            DeviceType::Reserved0x57 => "Reserved 57h",
            DeviceType::Reserved0x58 => "Reserved 58h",
            DeviceType::Reserved0x59 => "Reserved 59h",
            DeviceType::Reserved0x5A => "Reserved 5Ah",
            DeviceType::Reserved0x5B => "Reserved 5Bh",
            DeviceType::Reserved0x5C => "Reserved 5Ch",
            DeviceType::Reserved0x5D => "Reserved 5Dh",
            DeviceType::Reserved0x5E => "Reserved 5Eh",
            DeviceType::Reserved0x5F => "Reserved 5Fh",
            DeviceType::Reserved0x60 => "Reserved 60h",
            DeviceType::Reserved0x61 => "Reserved 61h",
            DeviceType::Reserved0x62 => "Reserved 62h",
            DeviceType::Reserved0x63 => "Reserved 63h",
            DeviceType::Reserved0x64 => "Reserved 64h",
            DeviceType::Reserved0x65 => "Reserved 65h",
            DeviceType::Reserved0x66 => "Reserved 66h",
            DeviceType::Reserved0x67 => "Reserved 67h",
            DeviceType::Reserved0x68 => "Reserved 68h",
            DeviceType::Reserved0x69 => "Reserved 69h",
            DeviceType::Reserved0x6A => "Reserved 6Ah",
            DeviceType::Reserved0x6B => "Reserved 6Bh",
            DeviceType::Reserved0x6C => "Reserved 6Ch",
            DeviceType::Reserved0x6D => "Reserved 6Dh",
            DeviceType::Reserved0x6E => "Reserved 6Eh",
            DeviceType::Reserved0x6F => "Reserved 6Fh",
            DeviceType::Reserved0x70 => "Reserved 70h",
            DeviceType::Reserved0x71 => "Reserved 71h",
            DeviceType::Reserved0x72 => "Reserved 72h",
            DeviceType::Reserved0x73 => "Reserved 73h",
            DeviceType::Reserved0x74 => "Reserved 74h",
            DeviceType::Reserved0x75 => "Reserved 75h",
            DeviceType::Reserved0x76 => "Reserved 76h",
            DeviceType::Reserved0x77 => "Reserved 77h",
            DeviceType::Reserved0x78 => "Reserved 78h",
            DeviceType::Reserved0x79 => "Reserved 79h",
            DeviceType::Reserved0x7A => "Reserved 7Ah",
            DeviceType::Reserved0x7B => "Reserved 7Bh",
            DeviceType::Reserved0x7C => "Reserved 7Ch",
            DeviceType::Reserved0x7D => "Reserved 7Dh",
            DeviceType::Reserved0x7E => "Reserved 7Eh",
            DeviceType::Reserved0x7F => "Reserved 7Fh",
            DeviceType::Reserved0x80 => "Reserved 80h",
            DeviceType::Reserved0x81 => "Reserved 81h",
            DeviceType::Reserved0x82 => "Reserved 82h",
            DeviceType::Reserved0x83 => "Reserved 83h",
            DeviceType::Reserved0x84 => "Reserved 84h",
            DeviceType::Reserved0x85 => "Reserved 85h",
            DeviceType::Reserved0x86 => "Reserved 86h",
            DeviceType::Reserved0x87 => "Reserved 87h",
            DeviceType::Reserved0x88 => "Reserved 88h",
            DeviceType::Reserved0x89 => "Reserved 89h",
            DeviceType::Reserved0x8A => "Reserved 8Ah",
            DeviceType::Reserved0x8B => "Reserved 8Bh",
            DeviceType::Reserved0x8C => "Reserved 8Ch",
            DeviceType::Reserved0x8D => "Reserved 8Dh",
            DeviceType::Reserved0x8E => "Reserved 8Eh",
            DeviceType::Reserved0x8F => "Reserved 8Fh",
            DeviceType::Reserved0x90 => "Reserved 90h",
            DeviceType::Reserved0x91 => "Reserved 91h",
            DeviceType::Reserved0x92 => "Reserved 92h",
            DeviceType::Reserved0x93 => "Reserved 93h",
            DeviceType::Reserved0x94 => "Reserved 94h",
            DeviceType::Reserved0x95 => "Reserved 95h",
            DeviceType::Reserved0x96 => "Reserved 96h",
            DeviceType::Reserved0x97 => "Reserved 97h",
            DeviceType::Reserved0x98 => "Reserved 98h",
            DeviceType::Reserved0x99 => "Reserved 99h",
            DeviceType::Reserved0x9A => "Reserved 9Ah",
            DeviceType::Reserved0x9B => "Reserved 9Bh",
            DeviceType::Reserved0x9C => "Reserved 9Ch",
            DeviceType::Reserved0x9D => "Reserved 9Dh",
            DeviceType::Reserved0x9E => "Reserved 9Eh",
            DeviceType::Reserved0x9F => "Reserved 9Fh",
            DeviceType::Reserved0xA0 => "Reserved A0h",
            DeviceType::Reserved0xA1 => "Reserved A1h",
            DeviceType::Reserved0xA2 => "Reserved A2h",
            DeviceType::Reserved0xA3 => "Reserved A3h",
            DeviceType::Reserved0xA4 => "Reserved A4h",
            DeviceType::Reserved0xA5 => "Reserved A5h",
            DeviceType::Reserved0xA6 => "Reserved A6h",
            DeviceType::Reserved0xA7 => "Reserved A7h",
            DeviceType::Reserved0xA8 => "Reserved A8h",
            DeviceType::Reserved0xA9 => "Reserved A9h",
            DeviceType::Reserved0xAA => "Reserved AAh",
            DeviceType::Reserved0xAB => "Reserved ABh",
            DeviceType::Reserved0xAC => "Reserved ACh",
            DeviceType::Reserved0xAD => "Reserved ADh",
            DeviceType::Reserved0xAE => "Reserved AEh",
            DeviceType::Reserved0xAF => "Reserved AFh",
            DeviceType::Reserved0xB0 => "Reserved B0h",
            DeviceType::Reserved0xB1 => "Reserved B1h",
            DeviceType::Reserved0xB2 => "Reserved B2h",
            DeviceType::Reserved0xB3 => "Reserved B3h",
            DeviceType::Reserved0xB4 => "Reserved B4h",
            DeviceType::Reserved0xB5 => "Reserved B5h",
            DeviceType::Reserved0xB6 => "Reserved B6h",
            DeviceType::Reserved0xB7 => "Reserved B7h",
            DeviceType::Reserved0xB8 => "Reserved B8h",
            DeviceType::Reserved0xB9 => "Reserved B9h",
            DeviceType::Reserved0xBA => "Reserved BAh",
            DeviceType::Reserved0xBB => "Reserved BBh",
            DeviceType::Reserved0xBC => "Reserved BCh",
            DeviceType::Reserved0xBD => "Reserved BDh",
            DeviceType::Reserved0xBE => "Reserved BEh",
            DeviceType::Reserved0xBF => "Reserved BFh",
            DeviceType::Reserved0xC0 => "Reserved C0h",
            DeviceType::Reserved0xC1 => "Reserved C1h",
            DeviceType::Reserved0xC2 => "Reserved C2h",
            DeviceType::Reserved0xC3 => "Reserved C3h",
            DeviceType::Reserved0xC4 => "Reserved C4h",
            DeviceType::Reserved0xC5 => "Reserved C5h",
            DeviceType::Reserved0xC6 => "Reserved C6h",
            DeviceType::Reserved0xC7 => "Reserved C7h",
            DeviceType::Reserved0xC8 => "Reserved C8h",
            DeviceType::Reserved0xC9 => "Reserved C9h",
            DeviceType::Reserved0xCA => "Reserved CAh",
            DeviceType::Reserved0xCB => "Reserved CBh",
            DeviceType::Reserved0xCC => "Reserved CCh",
            DeviceType::Reserved0xCD => "Reserved CDh",
            DeviceType::Reserved0xCE => "Reserved CEh",
            DeviceType::Reserved0xCF => "Reserved CFh",
            DeviceType::Reserved0xD0 => "Reserved D0h",
            DeviceType::Reserved0xD1 => "Reserved D1h",
            DeviceType::Reserved0xD2 => "Reserved D2h",
            DeviceType::Reserved0xD3 => "Reserved D3h",
            DeviceType::Reserved0xD4 => "Reserved D4h",
            DeviceType::Reserved0xD5 => "Reserved D5h",
            DeviceType::Reserved0xD6 => "Reserved D6h",
            DeviceType::Reserved0xD7 => "Reserved D7h",
            DeviceType::Reserved0xD8 => "Reserved D8h",
            DeviceType::Reserved0xD9 => "Reserved D9h",
            DeviceType::Reserved0xDA => "Reserved DAh",
            DeviceType::Reserved0xDB => "Reserved DBh",
            DeviceType::Reserved0xDC => "Reserved DCh",
            DeviceType::Reserved0xDD => "Reserved DDh",
            DeviceType::Reserved0xDE => "Reserved DEh",
            DeviceType::Reserved0xDF => "Reserved DFh",
            DeviceType::Reserved0xE0 => "Reserved E0h",
            DeviceType::Reserved0xE1 => "Reserved E1h",
            DeviceType::Reserved0xE2 => "Reserved E2h",
            DeviceType::Reserved0xE3 => "Reserved E3h",
            DeviceType::Reserved0xE4 => "Reserved E4h",
            DeviceType::Reserved0xE5 => "Reserved E5h",
            DeviceType::Reserved0xE6 => "Reserved E6h",
            DeviceType::Reserved0xE7 => "Reserved E7h",
            DeviceType::Reserved0xE8 => "Reserved E8h",
            DeviceType::Reserved0xE9 => "Reserved E9h",
            DeviceType::Reserved0xEA => "Reserved EAh",
            DeviceType::Reserved0xEB => "Reserved EBh",
            DeviceType::Reserved0xEC => "Reserved ECh",
            DeviceType::Reserved0xED => "Reserved EDh",
            DeviceType::Reserved0xEE => "Reserved EEh",
            DeviceType::Reserved0xEF => "Reserved EFh",
            DeviceType::Reserved0xF0 => "Reserved F0h",
            DeviceType::Reserved0xF1 => "Reserved F1h",
            DeviceType::Reserved0xF2 => "Reserved F2h",
            DeviceType::Reserved0xF3 => "Reserved F3h",
            DeviceType::Reserved0xF4 => "Reserved F4h",
            DeviceType::Reserved0xF5 => "Reserved F5h",
            DeviceType::Reserved0xF6 => "Reserved F6h",
            DeviceType::Reserved0xF7 => "Reserved F7h",
            DeviceType::Reserved0xF8 => "Reserved F8h",
            DeviceType::Reserved0xF9 => "Reserved F9h",
            DeviceType::Reserved0xFA => "Reserved FAh",
            DeviceType::Reserved0xFB => "Reserved FBh",
            DeviceType::Reserved0xFC => "Reserved FCh",
            DeviceType::Reserved0xFD => "Reserved FDh",
            DeviceType::Reserved0xFE => "Reserved FEh",
            DeviceType::Reserved0xFF => "Reserved FFh",
        };
        write!(f, "{}", device_type)
    }
}